# Generated by Django 4.2.6 on 2023-11-16 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0003_source_img_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='img',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
