# Generated by Django 4.2.6 on 2023-11-16 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0004_alter_headline_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='img',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
