# Generated by Django 4.2.6 on 2023-11-30 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0002_userconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userconfig',
            name='id',
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
