# Generated by Django 4.2.6 on 2023-11-30 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_remove_userconfig_id_alter_userconfig_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfig',
            name='email_settings',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='register.emailsettings'),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='export_settings',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='register.exportsettings'),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='text_settings',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='register.textsettings'),
        ),
    ]
