# Generated by Django 4.2.6 on 2023-11-30 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_alter_userconfig_email_settings_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailsettings',
            old_name='is_active',
            new_name='is_email_notifications_active',
        ),
        migrations.RenameField(
            model_name='textsettings',
            old_name='is_active',
            new_name='is_text_notifications_active',
        ),
    ]
